// fetch provinces
export const FETCH_PROVINCES_PROCESS = "FETCH_PROVINCES_PROCESS";

export const FETCH_PROVINCES_SUCCESS = "FETCH_PROVINCES_SUCCESS";


// fetch districts
export const FETCH_DISTRICTS_PROCESS = "FETCH_DISTRICTS_PROCESS";

export const FETCH_DISTRICTS_SUCCESS = "FETCH_DISTRICTS_SUCCESS";


// fetch wards
export const FETCH_WARDS_PROCESS = "FETCH_WARDS_PROCESS";

export const FETCH_WARDS_SUCCESS = "FETCH_WARDS_SUCCESS";

