name: Auto Backup (open PR to production_backup)

on:
  push:
    branches: [production]     # run when production changes

concurrency:
  group: "backup-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  open-backup-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout production (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: production

      - name: Set Git identity
        run: |
          git config user.name "ci-promote-bot"
          git config user.email "ci-promote-bot@users.noreply.github.com"

      - name: Fetch all remote branches
        run: |
          git fetch --no-tags --prune origin "+refs/heads/*:refs/remotes/origin/*"

      - name: Prepare backup branch (base production_backup; fast-forward with production)
        run: |
          set -e
          if git show-ref --verify --quiet refs/remotes/origin/production_backup; then
            git checkout -B production_backup origin/production_backup
          else
            git checkout -B production_backup origin/production
          fi
          git checkout -B ci/backup
          git merge --ff-only origin/production

      - name: Push ci/backup
        run: |
          set -e
          git push origin ci/backup --force-with-lease

      - name: Open/Update PR to production_backup (auto-delete ci branch on merge)
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/backup
          base: production_backup
          title: "Auto backup: production → production_backup"
          body: |
            This PR was auto-created after a push to `production`.
            - Type: fast-forward sync to backup
            - Source: "${{ github.repository }}@${{ github.sha }}"
          labels: auto-backup
          draft: false
          delete-branch: true
