name: Auto Backup (open PR to production_backup)

on:
  workflow_run:
    # MUST match your promote workflow's name exactly
    workflows: ["Auto Promote (open PR to production)"]
    types: [completed]

concurrency:
  group: "backup-${{ github.run_id }}"
  cancel-in-progress: false

jobs:
  open-backup-pr:
    # run only if the promote workflow finished successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write          # push ci branch
      pull-requests: write     # open/update PR

    steps:
      - name: Checkout default branch (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "ci-promote-bot"
          git config user.email "ci-promote-bot@users.noreply.github.com"

      - name: Fetch all remote branches
        run: |
          # Update remote-tracking refs only (do NOT overwrite local branches)
          git fetch --no-tags --prune origin "+refs/heads/*:refs/remotes/origin/*"

      - name: Decide if backup is needed
        id: need_backup
        shell: bash
        run: |
          set -e
          PROD=$(git rev-parse --verify "refs/remotes/origin/production" || echo "")
          BACK=$(git rev-parse --verify "refs/remotes/origin/production_backup" || echo "")
          if [ -z "$PROD" ]; then
            echo "No production branch yet → skip."
            echo "run=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          if [ -n "$BACK" ] && [ "$PROD" = "$BACK" ]; then
            echo "production == production_backup → nothing to do."
            echo "run=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "run=true" >> "$GITHUB_OUTPUT"

      - name: Prepare backup branch (production_backup → fast-forward with production)
        if: ${{ steps.need_backup.outputs.run == 'true' }}
        run: |
          set -e
          if git show-ref --verify --quiet refs/remotes/origin/production_backup; then
            git checkout -B production_backup origin/production_backup
          else
            git checkout -B production_backup origin/production
          fi
          git checkout -B ci/backup
          git merge --ff-only origin/production

      - name: Push ci/backup
        if: ${{ steps.need_backup.outputs.run == 'true' }}
        run: |
          set -e
          git push origin ci/backup --force-with-lease

      - name: Create/merge PR to production_backup (ci/backup → production_backup)
        if: ${{ steps.need_backup.outputs.run == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -e

          PR_NUMBER=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --state open \
            --base production_backup \
            --head ci/backup \
            --json number --jq '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            gh pr create \
              --repo "$GITHUB_REPOSITORY" \
              --base production_backup \
              --head ci/backup \
              --title "Auto backup: production → production_backup" \
              --body "Auto-created after a successful promote workflow." \
              --label auto-backup

            PR_NUMBER=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --state open \
              --base production_backup \
              --head ci/backup \
              --json number --jq '.[0].number')
          fi

          if [ -z "$PR_NUMBER" ]; then
            echo "No open PR could be found or created for ci/backup → production_backup"
            exit 1
          fi

          gh pr merge "$PR_NUMBER" --merge --auto --repo "$GITHUB_REPOSITORY"
