name: Auto Promote (open PR to production)

on:
  pull_request:
    types: [closed]           # run only when a PR targeting development is closed
    branches: [development]   # base branch = development

concurrency:
  group: promote-${{ github.ref }}  # avoid overlapping promotions on same ref
  cancel-in-progress: false

jobs:
  open-promote-pr:
    if: github.event.pull_request.merged == true   # proceed only if the PR was merged
    runs-on: ubuntu-latest
    permissions:
      contents: write          # push temp branch
      pull-requests: write     # open/update PR

    steps:
      - name: Checkout development (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # full history for safe merges
          ref: development

      - name: Set Git identity (for any local commits if needed)
        run: |
          git config user.name  "ci-promote-bot"
          git config user.email "ci-promote-bot@users.noreply.github.com"

      - name: Fetch all remote branches
        run: |
          # Update remote-tracking refs only (do NOT overwrite local branches)
          git fetch --no-tags --prune origin "+refs/heads/*:refs/remotes/origin/*"

      - name: Prepare promote branch (base: production → ff with development)
        run: |
          set -e
          # Start from current production; if production doesn't exist yet, start from development
          if git show-ref --verify --quiet refs/remotes/origin/production; then
            git checkout -B production origin/production
          else
            git checkout -B production origin/development
          fi

          # Create/update the fixed CI branch from production
          git checkout -B ci/promote

          # Fast-forward CI branch with development (fail if not fast-forwardable)
          git merge --ff-only origin/development

      - name: Push ci/promote (force-with-lease to update safely)
        run: |
          set -e
          git push origin ci/promote --force-with-lease

      - name: Open/Update PR to production (auto-delete head branch on merge)
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/promote                 # fixed CI branch to avoid branch clutter
          base: production
          title: "Auto promote: development → production"
          body: |
            This PR was auto-created after a merge into `development`.
            - Type: fast-forward promotion (no CI merge commits)
            - Source: `${{ github.repository }}@${{ github.sha }}`
          labels: auto-promote
          draft: false
          delete-branch: true               # delete ci/promote after PR is merged
